apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
  labels:
    app.kubernetes.io/name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: superset
  template:
    metadata:
      labels:
        app.kubernetes.io/name: superset
    spec:
      containers:
        - name: postgres
          image: "tylerfowler/superset"
          env:
            - name: ADMIN_USERNAME
              value: admin
            - name: ADMIN_FIRST_NAME
              value: Admin
            - name: ADMIN_LAST_NAME
              value: User
            - name: ADMIN_EMAIL
              value: admin@aprovan.com
            - name: ADMIN_PWD
              value: superset
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: superset
spec:
  selector:
    app.kubernetes.io/name: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
